available_commands = [' add-contact (press enter)',
                      ' change <Name> <new_phone_number>',
                      ' delete-contact <Name>',
                      ' phone <Name>',
                      ' contacts',
                      ' change-email <Name> <New_Email>',
                      ' change-phone <Name> <Old_Phone> <New_Phone>',
                      ' change-address <Name> <New_Address>',
                      ' hello',
                      ' add-birthday <Name> <DD.MM.YYYY>',
                      ' change-birthday <Name> <DD.MM.YYYY>',
                      ' show-contact <Name>',
                      ' find-by-phone <Phone>',
                      ' find-by-address <Address>',
                      ' find-by-email <Email>',
                      ' find-by-birthday <Birthday>',
                      ' contacts',
                      ' add-birthday <Name> <DD.MM.YYYY>',
                      ' change-birthday <Name> <DD.MM.YYYY>',
                      ' birthdays <per_days>',
                      ' change-tag <ID> <old_tag> <new_tag>',
                      ' find-by-title <title>',
                      ' find-by-content <content>',
                      ' sort-by-tag <tag> <tag>',
                      ' show-note <ID>',
                      ' delete-note <ID>',
                      ' add-note',
                      ' notes',
                      ' exit',
                      ' close',
                      'add-contact (press enter)',
                      'change <Name> <new_phone_number>',
                      'change-email <Name> <New_Email>',
                      'change-phone <Name> <Old_Phone> <New_Phone>',
                      'change-address <Name> <New_Address>',
                      'delete-contact <Name>',
                      'phone <Name>',
                      ' find-by-tag <tag1>,<tag2>,...',
                      ' change-title <ID>',
                      ' change-content <ID>',
                      ' add-tag <ID> <tag_value>'
                      ' help',
                      'change <Name> <new_phone_number>',
                      'contacts',
                      'add-birthday <Name> <DD.MM.YYYY>',
                      'change-birthday <Name> <DD.MM.YYYY>',
                      'show-birthday <Name>',
                      'show-contact <Name>',
                      'find-by-phone <Phone>',
                      'find-by-address <Address>',
                      'find-by-email <Email>',
                      'find-by-birthday <Birthday>',
                      'change-tag <ID> <old_tag> <new_tag>',
                      'find-by-title <title>',
                      'find-by-content <content>',
                      'sort-by-tag <tag> <tag>',
                      'show-note <ID>',
                      'delete-note <ID>',
                      'show-birthday <Name>',
                      'birthdays <per_days>',
                      'add-note',
                      'notes',
                      'exit',
                      'close',
                      'help',
                      'find-by-tag <tag1>,<tag2>,...',
                      'change-title <ID>',
                      'change-content <ID>',
                      'add-tag <ID> <tag_value>'
                      ]

commands_description = [
    {"Command": "add - to add new contact",
     "Format": "add",
     "Example": "add Ann 1236547890",
     },
    {"Command": "change-name",
     "Format": "change <old_name> <new_name>",
     "Example": "change Ann Luci"
     },
    {"Command": "close - to close assistant",
     "Format": "close",
     "Example": "close"
     }
    # },
    #  {"Command": "phone",
    #  "Format": "phone <Name>",
    #  "Example": "phone Ann",
    #  "Result": "phone output by name"},
    #  {"Command": "contacts",
    #  "Format": "contacts",
    #  "Example": "contacts",
    #  "Result": "contact list"},
    #  {"Command": "add-birthday",
    #  "Format": "add-birthday <Name>",
    #  "Example": "add-birthday Ann",
    #  "Result": "add date of birth"},
    #  {"Command": "show-birthday",
    #  "Format": "show-birthday <in how many days>",
    #  "Example": "show-birthday 7"
    #  },
    #  {"Command": "notes",
    #  "Format": "notes <title> <text>",
    #  "Example": "notes <Reminder> <How to be beautiful. Apply the cream to the face every night.>"},
    #  {"Command": "birthday",
    #  "Format": "birthday <Name>",
    #  "Example": "birthday <Ann>"},

]
