available_commands = [' add <Name> <phone_namber>',
                      ' change <Name> <new_phone_number>',
                      ' phone <Name>',
                      ' contacts',
                      ' hello',
                      ' add-birthday <Name> <DD.MM.YYYY>',
                      ' show-birthday <Name>',
                      ' birthdays',
                      ' add-note',
                      ' notes',
                      ' exit',
                      ' close',
                      'add <Name> <phone_namber>',
                      'change <Name> <new_phone_number>',
                      'phone <Name>',
                      'contacts',
                      'hello',
                      'add-birthday <Name> <DD.MM.YYYY>',
                      'show-birthday <Name>',
                      'birthdays',
                      'add-note',
                      'notes',
                      'exit',
                      'close',
                      'help',
                      ' help']

commands_description = [
    {"Command": "add",
     "Format": "add <Name> <phone_namber>",
     "Example": "add Ann 1236547890",
     "Restrictions": "Phone must be 10 digits"},
    {"Command": "hello",
     "Format": "hello",
     "Example": "hello"},
    {"Command": "change",
     "Format": "change <Name> <new_phone_number>",
     "Example": "change Ann 1236547890",
     "Restrictions": "Phone must be 10 digits"},

]
