available_commands = [' add (press enter)',
                      ' change <Name> <new_phone_number>',
                      ' delete <Name>',
                      ' phone <Name>',
                      ' contacts',
                      ' hello',
                      ' add-birthday <Name> <DD.MM.YYYY>',
                      ' change-birthday <Name> <DD.MM.YYYY>',
                      ' show-birthday <Name>',
                      ' show-contact <Name>',
                      ' find-by-phone <Phone>',
                      ' find-by-address <Address>',
                      ' find-by-email <Email>',
                      ' find-by-birthday <Birthday>',
                      ' birthdays',
                      ' birthdays <per_days>',
                      ' add-note',
                      ' notes',
                      ' exit',
                      ' close',
                      'add (press enter)',
                      'change <Name> <new_phone_number>',
                      'delete <Name>',
                      'phone <Name>',
                      'contacts',
                      'hello',
                      'add-birthday <Name> <DD.MM.YYYY>',
                      'change-birthday <Name> <DD.MM.YYYY>',
                      'show-birthday <Name>',
                      'show-contact <Name>',
                      'find-by-phone <Phone>',
                      'find-by-address <Address>',
                      'find-by-email <Email>',
                      'find-by-birthday <Birthday>',
                      'birthdays',
                      'birthdays <per_days>',
                      'add-note',
                      'notes',
                      'exit',
                      'close',
                      'help',
                      ' help']

commands_description = [
    {"Command": "add - to add new contact",
     "Format": "add",
     "Example": "add Ann 1236547890",
     },
    {"Command": "hello",
     "Format": "hello",
     "Example": "hello"
     },
    {"Command": "change-name",
     "Format": "change <old_name> <new_name>",
     "Example": "change Ann Luci"
     },
    {"Command": "close - to close assistant",
     "Format": "close",
     "Example": "close"
     }
    # },
    #  {"Command": "phone",
    #  "Format": "phone <Name>",
    #  "Example": "phone Ann",
    #  "Result": "phone output by name"},
    #  {"Command": "contacts",
    #  "Format": "contacts",
    #  "Example": "contacts",
    #  "Result": "contact list"},
    #  {"Command": "add-birthday",
    #  "Format": "add-birthday <Name>",
    #  "Example": "add-birthday Ann",
    #  "Result": "add date of birth"},
    #  {"Command": "show-birthday",
    #  "Format": "show-birthday <in how many days>",
    #  "Example": "show-birthday 7"
    #  },
    #  {"Command": "notes",
    #  "Format": "notes <title> <text>",
    #  "Example": "notes <Reminder> <How to be beautiful. Apply the cream to the face every night.>"},
    #  {"Command": "birthday",
    #  "Format": "birthday <Name>",
    #  "Example": "birthday <Ann>"},

]
