available_commands = [' add <Name> <phone_namber>',
                      ' change <Name> <new_phone_number>',
                      ' phone <Name>',
                      ' contacts',
                      ' hello',
                      ' add-birthday <Name> <DD.MM.YYYY>',
                      ' show-birthday <Name>',
                      ' birthdays',
                      ' add-note',
                      ' notes',
                      ' exit',
                      ' close',
                      'add <Name> <phone_namber>',
                      'change <Name> <new_phone_number>',
                      'phone <Name>',
                      'contacts',
                      'hello',
                      'add-birthday <Name> <DD.MM.YYYY>',
                      'show-birthday <Name>',
                      'birthdays',
                      'add-note',
                      'notes',
                      'exit',
                      'close',
                      'help',
                      ' help']

commands_description = [
    {"Command": "add",
     "Format": "add <Name> <phone_namber>",
     "Example": "add Ann 1236547890",
     "Restrictions": "Phone must be 10 digits"},
    {"Command": "hello",
     "Format": "hello",
     "Example": "hello",
     "Result": "transition to management"},
    {"Command": "change",
     "Format": "change <Name> <new_phone_number>",
     "Example": "change Ann 1236547890",
     "Restrictions": "Phone must be 10 digits"},
     {"Command": "'close' or 'exit'",
     "Format": "'close' or 'exit'",
     "Example": "exit",
     "Result": "exit the program"},
     {"Command": "phone",
     "Format": "phone <Name>",
     "Example": "phone Ann",
     "Result": "phone output by name"},
     {"Command": "contacts",
     "Format": "contacts",
     "Example": "contacts",
     "Result": "contact list"},
     {"Command": "add-birthday",
     "Format": "add-birthday <Name>",
     "Example": "add-birthday Ann",
     "Result": "add date of birth"},
     {"Command": "show-birthday",
     "Format": "show-birthday <in how many days>",
     "Example": "show-birthday 7",
     "Result": "output of the list of birthdays for the next 7 days"},
     {"Command": "notes",
     "Format": "notes <title> <text>",
     "Example": "notes <Reminder> <How to be beautiful. Apply the cream to the face every night.>"},

]
